config/routes.rb
Bem::Application.routes.draw do

  resources :activation

  resources :carts

  get "store/index"

  resources :line_items do as_routes end

  match '/cart',                   :to => 'orders#cart_in_store'
  match '/orders/show_order',      :to => 'orders#show_order'
  match '/orders/new_in_store',    :to => 'orders#new_in_store'
  match '/orders/edit_in_store',   :to => 'orders#edit_in_store'
  match '/orders/create_in_store', :to => 'orders#create_in_store'

  resources :orders     do as_routes end
  resources :categories do as_routes end
  resources :products   do as_routes end

  match '/product_listing',    :to => 'products#listing'

  resources :sessions, :only => [:new, :create, :destroy]

  match '/users/edit_profile',   :to => 'users#edit_profile'
  match '/users/update_profile', :to => 'users#update_profile'
  match '/users/show_profile',   :to => 'users#show_profile'
  match '/users/confirmation',   :to => 'users#show_profile'

  resources :users do as_routes end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  resources :password_resets

  match '/home',    :to => 'store#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/store',   :to => 'store#index'
  match '/',        :to => 'store#index'
  match '/root',    :to => 'store#index'

  root :to => 'store#index', :as => 'store'

end

app/views/orders_in_store/_form.html.erb
<%= form_for(@order, :url => { :action => "create_in_store" }) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %>
      prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />

    <%= f.text_area :address, :rows => 3, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, :size => 40 %>
  </div>

  <div class="field">
    <%= f.label :pay_type %><br />
    <%= f.select :pay_type, Order::PAYMENT_TYPES,
                  :prompt => 'Select a payment method' %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Order' %>

  </div>
<% end %>

app/views/orders_in_store/_summary.html.haml
%table
  %tr
    %td{:style => 'vertical-align: top'}
      %h1
        Please verify or update the items in your order
      %div#ordered_items
        = render(:partial => 'line_items/ordered_items')
      %div{:style => 'align: center; vertical-align: bottom'}
      = button_to "Continue Shopping", home_path
  %tr
    %td
      %h1
        Please verify or update your address and payment type for this order
      = form_for(@order, :url => { :action => "create_in_store" }) do |f|
        - if @order.errors.any?
          %div{ :id => "error_explanation"}
            %h2
              = pluralize(@order.errors.count, "error")
              prohibited this order from being saved:
            %ul
              - @order.errors.full_messages.each do |msg|
                %li= msg

        -u = current_user
        %div{ :class => "field"}
          = f.label 'Order name'
          - now = Time.now
          - the_order_time = now.to_formatted_s(:long_ordinal) + ":#{now.sec}"
          - the_order_name = "#{u.first_name} #{u.last_name}'s order on #{the_order_time}"
          = f.text_field :name, :size => 40, :value => the_order_name, :disabled => false

        %div{ :class => "field"}
          = f.label :email
          = f.text_field :email, :size => 40, :value => u.email, :disabled => false

        %div{ :class => "field"}
          = f.label :address
          - order_address = u.address + "\n" + u.city +  "\n" + u.country +  "\n" + u.phone 
          = f.text_area :address, :rows => 4, :cols => 40, :value => order_address, :disabled => false

        %div{ :class => "field"}
          = f.label :pay_type
          //= f.select :pay_type, Order::PAYMENT_TYPES, :prompt => 'Select a payment method'
          = f.select :pay_type, Order::PAYMENT_TYPES

        %div{ :class => "actions", :style => 'align: center; vertical-align: bottom' }
          = f.submit 'Place your order'
      = button_to "Continue Shopping", home_path

app/views/orders_in_store/cart.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Items in your cart</legend>
    <div id='ordered_items'>
      <%= render(:partial => 'line_items/ordered_items') %>
    </div>
    <%= button_to "Continue Shopping", home_path %>
    <%= button_to "Checkout", :action => 'new_in_store', :controller => :orders, :method => :get %>
    <%= button_to 'Empty cart', @cart, :method => :delete,
        :confirm => "Press 'Ok' to delete all items in this cart, 'Cancel' to keep them" %>
  </fieldset>
</div>

app/views/orders_in_store/cart.html.haml
.depot_form
  %fieldset
    %legend Items in your cart
    #ordered_items
      = render(:partial => 'line_items/ordered_items')
    = button_to "Continue Shopping", home_path
    = button_to "Checkout", :action => 'new_in_store', :controller => :orders, :method => :get
    = button_to 'Empty cart', @cart, :method => :delete,                               |
      :confirm => "Press 'Ok' to delete all items in this cart, 'Cancel' to keep them" |

app/views/orders_in_store/edit.html.erb
<h1>Editing order</h1>

<%= render 'orders_in_store/form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders_in_store/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Pay type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.name %></td>
    <td><%= order.address %></td>
    <td><%= order.email %></td>
    <td><%= order.pay_type %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders_in_store/index.html.haml
%h1 Listing orders
%table
  %tr
    %th Name
    %th Address
    %th Email
    %th Pay type
    %th
    %th
    %th
  - @orders.each do |order|
    %tr
      %td= order.name
      %td= order.address
      %td= order.email
      %td= order.pay_type
      %td= link_to 'Show', order
      %td= link_to 'Edit', edit_order_path(order)
      %td= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Order', new_order_path

app/views/orders_in_store/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Please Update or Confirm Your Order</legend>
    <%= render 'orders_in_store/summary' %>
  </fieldset>
</div>

app/views/orders_in_store/new.html.haml
.depot_form
  %fieldset
    %legend Please Update or Confirm Your Order
    = render 'orders_in_store/summary'

app/views/orders_in_store/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @order.name %>
</p>

<p>
  <b>Address:</b>
  <%= @order.address %>
</p>

<p>
  <b>Email:</b>
  <%= @order.email %>
</p>

<p>
  <b>Pay type:</b>
  <%= @order.pay_type %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders_in_store/show.html.haml
.depot_form
  %fieldset
    %legend Your Order
    .field
      %label.show Order Name:
      .data
        = @order.name
    .field
      %label.show Address:
      .data
        = @order.address
    .field
      %label.show Email:
      .data
        = @order.email
    .field
      %label.show Payment Type:
      .data
        = @order.pay_type
    .field
      %label.show Order Items:
      .data
        %table
          %tr
            %th{:style => 'padding: 5px'}
              Quantity
            %th{:style => 'padding: 5px'} Item
            %th{:style => 'padding: 5px'}
              Unit
              %br
              Price
            %th{:style => 'padding: 5px'} Picture
            %th{:style => 'padding: 5px'} Price
          - grand_total_price = 0
          - @order.line_items.each do |item|
            -grand_total_price += item.total_price
            %tr
              %td{:style => 'padding: 5px'}
                = item.quantity
              %td{:style => 'padding: 5px'}
                = item.product.title
              %td{:style => 'padding: 5px'}
                = item.product.price
              %td{:style => 'padding: 5px'}
                -unless item.product.image_url.blank?
                  = image_tag(item.product.image_url(:thumb_small), :size => '50x50')
              %td{:style => 'padding: 5px;text-align:right'}
                = item.total_price
          %tr{:class => "total_line"}
            %td{:colspan => "4", :style => 'padding: 5px'}Total
            %td{:class => "total_cell", :style => 'padding: 5px;text-align:right'}= number_to_currency(grand_total_price, :locale => :lb)