config/routes.rb
Bem::Application.routes.draw do

  resources :activation

  resources :carts

  get "store/index"

  resources :line_items do as_routes end

  match '/cart',                   :to => 'orders#cart_in_store'
  match '/orders/show_order',      :to => 'orders#show_order'
  match '/orders/new_in_store',    :to => 'orders#new_in_store'
  match '/orders/edit_in_store',   :to => 'orders#edit_in_store'
  match '/orders/create_in_store', :to => 'orders#create_in_store'

  resources :orders     do as_routes end
  resources :categories do as_routes end
  resources :products   do as_routes end

  match '/product_listing',    :to => 'products#listing'

  resources :sessions, :only => [:new, :create, :destroy]

  match '/users/edit_profile',   :to => 'users#edit_profile'
  match '/users/update_profile', :to => 'users#update_profile'
  match '/users/show_profile',   :to => 'users#show_profile'
  match '/users/confirmation',   :to => 'users#show_profile'

  resources :users do as_routes end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  resources :password_resets

  match '/home',    :to => 'store#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/store',   :to => 'store#index'
  match '/',        :to => 'store#index'
  match '/root',    :to => 'store#index'

  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id, quantity=1)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = line_items.build(:product_id => product_id)
      current_item.quantity = quantity.to_i
    end
    if current_item.quantity < 0
      current_item.quantity = 0
    end
    current_item
  end

  def remove_line_item(line_item)
    current_item = line_item
    if current_item
      current_item.quantity = 0
      current_item.cart    = nil
      current_item.product = nil
      current_item.order   = nil
      current_item.save
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end

  # return name for activescaffold
  def name
    id
  end
end

# == Schema Information
# Schema version: 20110513044037
#
# Table name: carts
#
#  id         :integer(4)      not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout 'store'

  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(store_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<div class="cart_title">Your Cart</div>
<table>
  <%= render(cart.line_items) %>

  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price, :locale => :lb) %></td>

  </tr>

</table>

<%= button_to "Checkout", :action => 'new_in_store', :controller => :orders, :method => :get %>
<%= button_to 'Empty cart', cart, :method => :delete,
    :confirm => "Press 'Ok' to delete all items in this cart, 'Cancel' to keep them" %>
<% end %>

app/views/carts/_cart.html.haml
- unless cart.line_items.empty?
  .cart_title Your Cart
  %table
    = render(cart.line_items)
    %tr.total_line
      %td{:colspan => "2"} Total
      %td.total_cell= number_to_currency(cart.total_price, :locale => :lb)
  = button_to "Checkout", :action => 'new_in_store', :controller => :orders, :method => :get
  = button_to 'Empty cart', cart, :method => :delete,                                |
    :confirm => "Press 'Ok' to delete all items in this cart, 'Cancel' to keep them" |

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/_form.html.haml
= form_for(@cart) do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2
        = pluralize(@cart.errors.count, "error")
        prohibited this cart from being saved:
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/edit.html.haml
%h1 Editing cart
= render 'form'
= link_to 'Show', @cart
|
\#{link_to 'Back', carts_path}

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/index.html.haml
%h1 Listing carts
%table
  %tr
    %th
    %th
    %th
  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Cart', new_cart_path

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/new.html.haml
%h1 New cart
= render 'form'
= link_to 'Back', carts_path

app/views/carts/show.html.erb
<%= render @cart %>

app/views/carts/show.html.haml
= render @cart