config/routes.rb
Bem::Application.routes.draw do

  resources :activation

  resources :carts

  get "store/index"

  resources :line_items do as_routes end

  match '/cart',                   :to => 'orders#cart_in_store'
  match '/orders/show_order',      :to => 'orders#show_order'
  match '/orders/new_in_store',    :to => 'orders#new_in_store'
  match '/orders/edit_in_store',   :to => 'orders#edit_in_store'
  match '/orders/create_in_store', :to => 'orders#create_in_store'

  resources :orders     do as_routes end
  resources :categories do as_routes end
  resources :products   do as_routes end

  match '/product_listing',    :to => 'products#listing'

  resources :sessions, :only => [:new, :create, :destroy]

  match '/users/edit_profile',   :to => 'users#edit_profile'
  match '/users/update_profile', :to => 'users#update_profile'
  match '/users/show_profile',   :to => 'users#show_profile'
  match '/users/confirmation',   :to => 'users#show_profile'

  resources :users do as_routes end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  resources :password_resets

  match '/home',    :to => 'store#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/store',   :to => 'store#index'
  match '/',        :to => 'store#index'
  match '/root',    :to => 'store#index'

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <% if is_admin? %>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
      <% end %>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      - if is_admin?
        %li= link_to "Products", products_path
        %li= link_to "Categories", categories_path
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, product_listing_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "Products", product_listing_path %></li>
      <% if is_admin? %>
        <li><%= link_to "Admin", products_path %></li>
      <% end %>
      <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
        <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>

    </ul>
  </nav>
</header>

app/views/layouts/_header.html.haml
%header
  = link_to logo, product_listing_path
  %nav.round
    %ul
      %li= link_to "Home", home_path
      %li= link_to "Products", product_listing_path
      - if is_admin?
        %li= link_to "Admin", products_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'
/[if lt IE 8] <haml:loud> stylesheet_link_tag 'blueprint/ie' </haml:loud>

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Beyt El Mouneh
    = stylesheet_link_tag :all
    //= javascript_include_tag :defaults
    = stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/ui-lightness/jquery-ui.css'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js'
    = javascript_include_tag 'rails_jquery.js'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js'
    = javascript_include_tag 'jquery-ui-timepicker-addon.js'
    = javascript_include_tag 'application.js'
    = active_scaffold_includes
    = csrf_meta_tag
  %body
    #wrapper
      .water_mark
        Beyt El Mouneh
      #top
        .main_navigation
          =link_to "Home", '/'
          |
          =link_to "Store", :controller => :pages, :action => :home
          |
          =link_to "Products", :controller => :products
          |
          =link_to "Categories", :controller => :categories
          |
          =link_to "Orders", :controller => :orders
          |
          =link_to "Order Line Items", :controller => :line_items
      #content
        #stuff
          %br
          = yield
          %br
          = link_to_function "test js", '$(this).html("js works")'
          %br
          %br
          = button_to_function "test button js", '$(this).after("<p>js button works</p>")'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js' %>
    <%= javascript_include_tag 'rails_jquery.js' %>
    <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js' %>
    <%= javascript_include_tag 'jquery-ui-timepicker-addon.js' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        <%= yield %>
      </section>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "Beyt El Mouneh | #{@title}"
    = stylesheet_link_tag :all
    = stylesheet_link_tag 'ui-lightness/jquery-ui-1_8_13_custom'
    = javascript_include_tag 'jquery_1_4_4_min'
    = javascript_include_tag 'rails_jquery'
    = javascript_include_tag 'jquery-ui-1_8_13_custom_min'
    = javascript_include_tag 'jquery-ui-timepicker-addon'
    = javascript_include_tag 'application.js'
    = active_scaffold_includes
    = csrf_meta_tag
  %body
    #wrapper
      -if Rails.env != 'production'
        .water_mark
          ="#{Rails.env}"
      -else
        - if Rails.root.to_s.include?('staging')
          .water_mark
            Staging Server
      .admin_mark
        ="Beyt el Mouneh Administration - Welcome (admin) #{current_user.name}"
      #top
        .main_navigation
          =link_to "Home", '/'
          |
          =link_to "Store", :controller => :store, :action => :index
          |
          =link_to "Products", :controller => :products
          |
          =link_to "Categories", :controller => :categories
          |
          =link_to "Orders", :controller => :orders
          |
          =link_to "Order Line Items", :controller => :line_items
          |
          =link_to "Users", :controller => :users
      #content
        #stuff
          %br
          = yield
          %br
          -if Rails.env != 'production'
            = link_to_function "test js", '$(this).html("js works")'
            %br
            %br
            = button_to_function "test button js", '$(this).after("<p>js button works</p>")'

app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beyt el Mouneh | <%= "#{@title}" %></title>
  <%= stylesheet_link_tag "store", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body id="store">
  <div id="logo">
    <%= image_tag("beyt_el_mouneh.jpg", :size => '90x60') %>
  </div>
  <div id="banner">
    <%= @page_title || "Beyt el Mouneh Online Store" %>
  </div>
  <% if Rails.env != 'production' %>
    <div class="water_mark">
      <%= "#{Rails.env}" %>
    </div>
  <% else %>
    <div class="water_mark">
      Beta Testing
    </div>
  <% end %>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
          <%= render @cart %>
        <% end %>
      <% end %>
      <a href="/">Home</a><br />
      <a href="/about">About</a><br />
      <a href="/contact">Contact</a><br />
      <a href="/cart">Your Cart</a><br />
      <br />
      <% if signed_in? %>
        <a href="/signout">Logout</a><br />
       <%= link_to "Profile", edit_user_path(current_user) %><br />
      <% else %>
        <a href="/signin">Login</a><br />
        <a href="/signup">Register</a><br />
      <% end %>
      <% if is_admin? %>
        <a href="/products">Admin</a><br />
      <% end %>
    </div>
    <div id="main">
      <% if not flash.empty? %>
        <section class="round">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, :class => "flash #{key}") %>
          <% end %>
        </section>
      <% end %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/store.html.haml
!!!
%html
  %head
    %title
      Beyt el Mouneh | #{"#{@title}"}
    = stylesheet_link_tag "store", :media => "all"
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body#store
    #logo
      = image_tag("beyt_el_mouneh.jpg", :size => '90x60')
    #banner
      = @page_title || "Beyt el Mouneh Online Store"
    - if Rails.env != 'production'
      .water_mark
        = "#{Rails.env}"
    - else
      - if Rails.root.to_s.include?('staging')
        .water_mark
          Staging Server
      -else
        .water_mark
          Production Beta Testing
    #columns
      #side
        - if @cart
          = hidden_div_if(@cart.line_items.empty?, :id => "cart") do
            = render @cart
        %a{:href => "/"} Home
        %br
        %a{:href => "/about"} About
        %br
        %a{:href => "/contact"} Contact
        %br
        %a{:href => "/cart"} Your Cart
        %br
        %br
        - if signed_in?
          %a{:href => "/signout"} Logout
          %br
          = link_to "Profile/Account for (#{current_user.name})", :controller => 'users', :action => 'show_profile', :id => current_user.id
          %br
        - else
          %a{:href => "/signin"} Login
          %br
          %a{:href => "/signup"} Register
          %br
        - if is_admin?
          %a{:href => "/products"} Admin
          %br
        %br
        = link_to "All Products", :controller => 'store', :action => 'index'
        %br
        -categories = Category.all
        -categories.each do |cat|
          -if cat.is_root?
            = content_tag(:div, link_to("#{cat.name}", {:controller => 'store', :action => 'index', :category_id => cat.id}), :class => 'categories')
            -if cat.has_children?
              = display_sub_categories(cat.children)

      #main
        - if not flash.empty?
          %section.round
            - flash.each do |key, value|
              = content_tag(:div, value, :class => "flash #{key}")
        = yield
#siteFooter
  %div.left
    =" ©2010-#{Time.now.year} Beyt El Mouneh. All Rights Reserved."
    %br
    %div.small_text
      = debug(params) if Rails.env.development?